src/AspNetCore.Knockout.DataTables.Web/Models/CustomFieldModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Knockout.DataTables.Web.Models
{
    public class CustomFieldModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}

src/AspNetCore.Knockout.DataTables.Web/Models/ErrorViewModel.cs
using System;

namespace AspNetCore.Knockout.DataTables.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/AspNetCore.Knockout.DataTables.Web/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCore.Knockout.DataTables.Web.Models;
using Newtonsoft.Json;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AspNetCore.Knockout.DataTables.Web.Controllers
{
    [Route("api/[controller]")]
    public class ApiController : Controller
    {
        // GET: api/values
        [HttpGet]
        public string Get()
        {
            return JsonConvert.SerializeObject(new
            {
                @default = new CustomFieldModel(),
                items = new List<CustomFieldModel>
                {
                    new CustomFieldModel
                    {
                        Id = 1,
                        Name = "FirstName",
                        Value = "Joshua",
                    },
                    new CustomFieldModel
                    {
                        Id = 2,
                        Name = "LastName",
                        Value = "Thompson",
                    }
            }
            });
        }
    }
}

src/AspNetCore.Knockout.DataTables.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCore.Knockout.DataTables.Web.Models;

namespace AspNetCore.Knockout.DataTables.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/AspNetCore.Knockout.DataTables.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/AspNetCore.Knockout.DataTables.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/AspNetCore.Knockout.DataTables.Web/Views/Home/Index.cshtml
@{
    Layout = "";
    ViewData["Title"] = "Home Page";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simple KnockoutJS Paging With DataTables.net</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.css">
    <link rel="stylehseet" type="text/css" href="//cdn.datatables.net/responsive/1.0.1/css/dataTables.responsive.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <button data-bind="click: create" class="btn btn-default">Create</button>

    <!-- the table we apply DataTables magic too, data populated with Knockout Foreach iterating over view model -->
    <table id="items" class="table table-striped table-bordered" data-bind="dataTable: items">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Value</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: items">
            <tr>
                <td><span data-bind="text: Id"></span></td>
                <td><span data-bind="text: Name"></span></td>
                <td><span data-bind="text: Value"></span></td>
                <td><button data-bind="click: $parent.delete" class="btn btn-default">Delete</button></td>
            </tr>
        </tbody>
    </table>

    <!-- Include ALL THE SCRIPTS -->
    <!-- jQuery http://jquery.com -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Bootstrap http://getbootstrap.com -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- KnockoutJS http://knockoutjs.com/ -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/knockout/3.2.0/knockout-min.js"></script>

    <!-- KnockoutJS Mapping http://knockoutjs.com/documentation/plugins-mapping.html -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/knockout.mapping/2.4.1/knockout.mapping.min.js"></script>

    <!-- jQuery DataTables http://datatables.net -->
    <script src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>

    <!-- Bootstrap DataTables http://www.datatables.net/manual/styling/bootstrap -->
    <script src="//cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.js"></script>

    <!-- Responsive DataTables http://www.datatables.net/extensions/responsive/ -->
    <script src="//cdn.datatables.net/responsive/1.0.1/js/dataTables.responsive.js"></script>

    <script>
        $(function () {
            function CustomFieldModel(data)
            {
                var self = this;

                self.Id = ko.observable(data.Id);
                self.Name = ko.observable(data.Name);
                self.Value = ko.observable(data.Value);
            }

            // knockout view model
            function ViewModel(data) {
                var self = this;
                self.items = ko.observableArray();
                self.dataTable = null;

                // knockout mapping JSON data to view model
                ko.mapping.fromJS(data, {}, self);

                self.create = function ()
                {
                    self.items.push(self.default);
                }    

                self.delete = function (element, event)
                {
                    self.items.remove(element);
                }
            }

            ko.bindingHandlers.dataTable = {
                init: function (element, valueAccessor, allBindingsAccessor) {
                    var value = valueAccessor(),
                        allBindings = ko.utils.unwrapObservable(allBindingsAccessor()),
                        options = allBindings.dataTableOptions || {},
                        $element = $(element);

                        model.dataTable = $element.DataTable(options);
                }
            }

            var model = null;
            // get data - sample data from Donors Choose API
            $.getJSON("@Url.Action("Get", "Api")", function (data) {
                model = new ViewModel(data);

                // bind the data
                ko.applyBindings(model);
            });
        });
    </script>

</body>
</html>

src/AspNetCore.Knockout.DataTables.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCore.Knockout.DataTables.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AspNetCore.Knockout.DataTables.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - AspNetCore.Knockout.DataTables.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>